version: '3'

services:
  mysql:
    image: mysql:5
    platform: linux/amd64
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-proot"
        ]
      timeout: 10s
      retries: 10
      start_period: 10s

  api:
    build: .
    environment:
      - APP_PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    ports:
      - 3000:3000